export const SERVICE_EXCEPTION_ENUM = {
    BASE: 30000,
    NOT_IMPLEMENTED: 30001,

    //Related to typeORM Entity task
    ENTITY_NOT_FOUND: 31000,
    ENTITY_CREATE_FAILED: 31001,
    ENTITY_UPDATE_FAILED: 31002,
    ENTITY_DELETE_FAILED: 31003,
    ENTITY_RESTORE_FAILED: 31004,

    SERVICE_RUN_ERROR: 35000,
    SERVICE_RUN_TIMEOUT: 38000,
    EXTERNAL_SERVICE_FAILED: 38001,
    DEPENDENCY_UNAVAILABLE: 38002, // If a required microservice, database, or external dependency is unavailable.
    RATE_LIMIT_EXCEEDED: 38003, // When the client exceeds the allowed number of requests within a time period.
    DB_CONFLICT: 38004, // Conflict in resource (e.g., unique constraint violation)

    DB_INCONSISTENCY: 39000,
} as const;

export const HTTP_STATUS = {
    CONTINUE: 100,
    SWITCHING_PROTOCOLS: 101,
    PROCESSING: 102,
    EARLYHINTS: 103,
    OK: 200,
    CREATED: 201,
    ACCEPTED: 202,
    NON_AUTHORITATIVE_INFORMATION: 203,
    NO_CONTENT: 204,
    RESET_CONTENT: 205,
    PARTIAL_CONTENT: 206,
    AMBIGUOUS: 300,
    MOVED_PERMANENTLY: 301,
    FOUND: 302,
    SEE_OTHER: 303,
    NOT_MODIFIED: 304,
    TEMPORARY_REDIRECT: 307,
    PERMANENT_REDIRECT: 308,
    BAD_REQUEST: 400,
    UNAUTHORIZED: 401,
    PAYMENT_REQUIRED: 402,
    FORBIDDEN: 403,
    NOT_FOUND: 404,
    METHOD_NOT_ALLOWED: 405,
    NOT_ACCEPTABLE: 406,
    PROXY_AUTHENTICATION_REQUIRED: 407,
    REQUEST_TIMEOUT: 408,
    CONFLICT: 409,
    GONE: 410,
    LENGTH_REQUIRED: 411,
    PRECONDITION_FAILED: 412,
    PAYLOAD_TOO_LARGE: 413,
    URI_TOO_LONG: 414,
    UNSUPPORTED_MEDIA_TYPE: 415,
    REQUESTED_RANGE_NOT_SATISFIABLE: 416,
    EXPECTATION_FAILED: 417,
    I_AM_A_TEAPOT: 418,
    MISDIRECTED: 421,
    UNPROCESSABLE_ENTITY: 422,
    FAILED_DEPENDENCY: 424,
    PRECONDITION_REQUIRED: 428,
    TOO_MANY_REQUESTS: 429,
    INTERNAL_SERVER_ERROR: 500,
    NOT_IMPLEMENTED: 501,
    BAD_GATEWAY: 502,
    SERVICE_UNAVAILABLE: 503,
    GATEWAY_TIMEOUT: 504,
    HTTP_VERSION_NOT_SUPPORTED: 505,
} as const;

export type ServiceExceptionKey = keyof typeof SERVICE_EXCEPTION_ENUM;
export type HttpStatusType = keyof typeof HTTP_STATUS;

export type HttpStatusValueType = (typeof HTTP_STATUS)[HttpStatusType];
export type ServiceExceptionValue = (typeof SERVICE_EXCEPTION_ENUM)[ServiceExceptionKey];
